INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (1, 'CHELSEA', 10.5, 6, 'leather');
INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (2, 'GOGO', 6.5, 6, 'rubber');
INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (3, 'GOGO', 7.5, 16, 'rubber');
INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (4, 'CHUKKA', 8.0, 8, 'leather');
INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (5, 'CHUKKA', 7.0, 3, 'canvas');