package com.codecademy.boots.entities;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import com.codecademy.boots.enums.BootType;

@Entity
@Table (name="BOOTS")
public class Boot {
    // ID -> unique identifier
    // autogenerated via GenerationType.IDENTITY (spring handles id creation!)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Notice how Enums are different from other fields with
    // annotation @Enumerated <- string enum types we can safely
    // add or delete diff enums w/o breaking the data model
    // unlike ordinal types
    @Column(name="TYPE")
    @Enumerated(EnumType.STRING)
    private BootType type;

    @Column(name="SIZE")
    private Float size;

    @Column(name="QUANTITY")
    private Integer quantity;

    @Column(name="MATERIAL")
    private String material;

    @Column(name="IS_BESTSELLER")
    private Boolean isBestseller;

    public Integer getId() {
        return this.id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    public BootType getType() {
        return this.type;
    }
    public void setType(BootType type) {
        this.type = type;
    }

    public Float getSize() {
        return this.size;
    }
    public void setSize(Float size) {
        this.size = size;
    }

    public Integer getQuantity() {
        return this.quantity;
    }
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getMaterial() {
        return this.material;
    }
    public void setMaterial(String material) {
        this.material = material;
    }

    public Boolean getIsBestseller() {
        return this.isBestseller;
    }
    public void setIsBestseller(Boolean isBestseller) {
        this.isBestseller = isBestseller;
    }

}